# frozen_string_literal: true

# Spec for the ActiveRecord autosave association method redefinition.
#
# ActiveRecord generates `autosave_associated_records_for_<assoc>` /
# `validate_associated_records_for_<assoc>` methods via `define_non_cyclic_method`
# -> `define_method(&block)` in autosave_association.rb. The method body is a
# Proc compiled in the main Ractor, so calling it from a worker raises
# "defined with an un-shareable Proc in a different Ractor" — which the shim's
# SymbolicTransport callback replay treats as skip-and-continue, silently
# no-oping nested attributes (built children never INSERTed) and `validate:`
# associations.
#
# The fix (prepare-time, after eager load but before the graph freeze) is
# `_redefine_ar_autosave_methods!`: it walks every AR model's associations and
# re-defines both method families as REAL `def`s whose body looks the
# reflection up from the class itself. Only methods whose source is Rails'
# autosave_association.rb are replaced (detected by
# `_rrs_rails_autosave_source?`); an app's own override wins.
#
# These unit specs run WITHOUT ActiveRecord loaded (the shim bundle has no
# Rails), so they cover the no-AR early path and the source-detection helper.
# The full worker behavior is covered by the test app's kino probes
# (nested_attributes / validate associations in stats_controller#assoc_probe).
#
# Run: bundle exec rake spec

require "minitest/autorun"
require "active_support/isolated_execution_state"
require_relative "../lib/ractor_rails_shim/roles/fallback_ies"
require_relative "../lib/ractor_rails_shim/patches"

class ActiverecordAutosavePatchSpec < Minitest::Spec
  it "defines the redefinition entrypoint _redefine_ar_autosave_methods!" do
    assert RactorRailsShim.respond_to?(:_redefine_ar_autosave_methods!, true),
           "_redefine_ar_autosave_methods! must be defined"
  end

  it "defines the source detector _rrs_rails_autosave_source?" do
    assert RactorRailsShim.respond_to?(:_rrs_rails_autosave_source?, true),
           "_rrs_rails_autosave_source? must be defined"
  end

  it "no-ops cleanly when ActiveRecord is not loaded" do
    # The early-install path runs before Rails boots; without
    # ActiveRecord::Base the entrypoint must return without error.
    assert_nil RactorRailsShim._redefine_ar_autosave_methods!
  end

  it "detects methods generated by Rails' autosave_association.rb" do
    klass = Class.new do
      # Source location can be faked via class_eval's (file, line) args —
      # this is exactly how a define_non_cyclic_method-generated method looks
      # to `instance_method(m).source_location`.
      class_eval("def generated_save_method; true; end",
                 "/some/gems/activerecord-8.0.0/lib/active_record/autosave_association.rb", 675)
      def app_override_method
        true
      end
    end

    assert RactorRailsShim._rrs_rails_autosave_source?(klass, :generated_save_method),
           "a define_non_cyclic_method-generated method must be detected"
    refute RactorRailsShim._rrs_rails_autosave_source?(klass, :app_override_method),
           "an app's own def must NOT be detected (its override must win)"
  end

  it "returns false (not an error) when the method is undefined" do
    klass = Class.new
    refute RactorRailsShim._rrs_rails_autosave_source?(klass, :no_such_method)
  end
end
