#!/usr/bin/env bash
# Reproduce the minimal Rails 8.1.3 test app used by the Phase 3 probes.
#
# The test app is NOT under version control (it lives in the system temp dir
# and may be wiped by the OS). This script regenerates it from scratch so a
# fresh session can run the probes without guessing the app's shape.
#
# Usage:
#   cd <this repo>
#   ./script/make_test_app.sh [dest_dir]
#
# dest_dir defaults to a temp dir under /var/folders/.../T/opencode/test_app
# (matching where Phase 3 ran). Override with an absolute path if you want
# it somewhere stable.
#
# After it finishes, it prints the exact probe commands to run.
set -euo pipefail

SHIM_DIR="$(cd "$(dirname "$0")/.." && pwd)"
DEST="${1:-$(mktemp -d)/test_app}"

echo "Creating minimal Rails app at: $DEST"
mkdir -p "$(dirname "$DEST")"

# Generate the app (--minimal keeps the dependency surface small, which is
# what the Phase 3 probes target).
rails new "$DEST" --minimal --skip-git --skip-bundle --skip-javascript \
  --skip-active-job --skip-action-mailer --skip-action-mailbox \
  --skip-action-text --skip-action-cable --skip-active-storage

cd "$DEST"

# Gemfile: add the shim (path), propshaft, sqlite3, puma, kino.
cat > Gemfile <<'RUBY'
source "https://rubygems.org"

gem "ractor-rails-shim", path: "SHIM_PATH_PLACEHOLDER"
gem "rails", "~> 8.1.3"
gem "propshaft"
gem "sqlite3", ">= 2.1"
gem "puma", ">= 5.0"
gem "kino"
gem "tzinfo-data", platforms: %i[ windows jruby ]

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
end
RUBY
sed -i '' "s|SHIM_PATH_PLACEHOLDER|$SHIM_DIR|" Gemfile

# config/boot.rb: install the shim before Rails.application is accessed.
cat > config/boot.rb <<'RUBY'
ENV["BUNDLE_GEMFILE"] ||= File.expand_path("../Gemfile", __dir__)

require "bundler/setup"

require "ractor_rails_shim"
RactorRailsShim.install
RUBY

# config/application.rb: keep the generated --minimal railties (active_model,
# active_record, action_controller, action_view, test_unit). The generated
# file already has the right railties for --minimal; just ensure
# config.generators.system_tests = nil (the generator adds it).
# We don't overwrite application.rb — the generated one is correct.

# config/routes.rb: the /up health check is generated by default. Confirm it.
# (rails new already adds `get "up" => "rails/health#show"`.)

# Production needs a secret_key_base. The probes set it via env var, so no
# credentials file is required.

bundle install

echo
echo "=== Test app ready at: $DEST ==="
echo
echo "To serve GET /up in a worker Ractor (returns HTTP 200):"
echo "  cd $DEST"
echo "  RAILS_ENV=production SECRET_KEY_BASE=dummy \\"
echo "    bundle exec ruby -e '\\"
echo "    require File.expand_path(\"config/boot\"); \\"
echo "    require File.expand_path(\"config/application\"); \\"
echo "    Bundler.require(*Rails.groups); Rails.application.initialize!; \\"
echo "    app = RactorRailsShim.make_app_shareable!(Rails.application); \\"
echo "    env = Ractor.make_shareable({\"REQUEST_METHOD\"=>\"GET\",\"PATH_INFO\"=>\"/up\",\"SCRIPT_NAME\"=>\"\",\"QUERY_STRING\"=>\"\",\"SERVER_NAME\"=>\"localhost\",\"SERVER_PORT\"=>\"9293\",\"HTTP_HOST\"=>\"localhost\",\"rack.url_scheme\"=>\"http\"}); \\"
echo "    r = Ractor.new(app,env){|a,e| re=e.to_h.merge(\"rack.input\"=>StringIO.new(\"\"),\"rack.errors\"=>StringIO.new(\"\"),\"rack.version\"=>[3,0]); begin; s,h,b=a.call(re); [s,h[\"content-type\"],b.each.to_a.join]; rescue=>ex; [:err,ex.class.name,ex.message[0,120]]; end }; \\"
echo "    puts r.value.inspect'"
echo
echo "To run the shim's unit specs (no Rails needed):"
echo "  cd $SHIM_DIR && bundle exec rake spec"
echo
echo "To run the integration spec (needs the test app + its bundle):"
echo "  cd $DEST"
echo "  bundle exec ruby -I$SHIM_DIR/lib -I$SHIM_DIR/spec \\"
echo "    -e'require \"minitest/autorun\"; require \"$SHIM_DIR/spec/integration_spec.rb\"'"